name: Testing out cache
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Test Mac build"
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
          working-directory: ios

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: '3.7.12'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Cache Pod Dependencies
        uses: actions/cache@v3
        with: 
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-