name: fb_chat_riverpod
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.0.1+2
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  json_serializable: ^6.1.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
